{
    "input": {
      "input_file_name": "/Users/lucamicheletti/GITHUB/dq_analysis_utils/macro/output/Data/LHC22o_apass2_muons.root",
      "input_name": [
      "Mass_PairsMuonSEPM_muonLowPt", 
      "PairsMuonSEPM_muonLowPt_Mass_Pt_Proj_0_Pt_2", 
      "PairsMuonSEPM_muonLowPt_Mass_Pt_Proj_2_Pt_6", 
      "PairsMuonSEPM_muonLowPt_Mass_Pt_Proj_6_Pt_20",
      "PairsMuonSEPM_muonLowPt_Mass_Rapidity_Proj_2.5_Y_3",
      "PairsMuonSEPM_muonLowPt_Mass_Rapidity_Proj_3_Y_3.5",
      "PairsMuonSEPM_muonLowPt_Mass_Rapidity_Proj_3.5_Y_4"],
      "pdf_dictionary": {
        "pdf": ["CB2", "VWG", "SUM"],
        "pdfName": ["Jpsi", "Bkg", "SUM"],
        "pdfNameForLegend": ["J/#psi", "Background", "Fit"],
        "pdfColor": [861, 1],
        "pdfStyle": [1, 2],
        "parVal": [
          [3.083, 9.5e-02, 1.089, 3.393, 2.097, 8.694],
          [1, 1, 1],
          [1000, 1000]
        ],
        "parLimMin": [
          [2.8, 6.0e-02, 1.0, 3.0, 2.0, 8.0],
          [-10, 0, -100],
          [100, 100]
        ],
        "parLimMax": [
          [3.2, 25.0e-02, 1.2, 3.5, 2.2, 9.0],
          [10, 100, 100],
          [10000000, 100000000]
        ],
        "parName": [
          ["mean_Jpsi", "width_Jpsi", "a_Jpsi", "b_Jpsi", "c_Jpsi", "d_Jpsi"],
          ["aa", "bb", "cc"],
          ["sig_Jpsi", "bkg"]
        ],
        "fitRangeMin": [2],
        "fitRangeMax": [5],
        "fitMethod": "likelyhood",
        "doResidualPlot": true,
        "doPullPlot": true, 
        "doCorrMatPlot": true,
        "doAlicePlot": true,
        "parForAlicePlot": ["mean_Jpsi", "width_Jpsi", "sig_Jpsi"],
        "parNameForAlicePlot": ["#mu_{J/#psi}", "#sigma_{J/#psi}", "#it{N}_{J/#psi}"],
        "text": [
          [0.20, 0.87, "LHC22o, pp #sqrt{#it{s}} = 13.6 TeV"], 
          [0.20, 0.80, "2.5 < #it{y} < 4, J/#psi #rightarrow #mu^{+}#mu^{-}"]
        ]
      }
    },
    "output": {
      "output_path": "output/LHC22o_apass2_CB2_VWG/"
    }
  }